# .github/workflows/ci.yml
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "11"

      - name: Set up Android SDK
        uses: actions/setup-android@v4
        with:
          api-level: 34
          build-tools: "34.0.0"
          components: |
            platform-tools
            platforms;android-34

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build and run all unit tests
        run: ./gradlew clean test
